### ISSUE TITLE
WebException with status "Created Created"

### ISSUE THREAD

**Issue by damdirt** [constantcontact/.net-sdk#15]
Hi, 

I'm currently working on a project where I have integrated a newsletter subscription system with your SDK. 
All I need is inside, so it's great ! :)

However, when I want to add a new contact to a list, a WebException is thrown in my code with status "Created Created" as you can seen below in the screenshot.
![ctct](https://f.cloud.github.com/assets/1451560/1299331/be2b5c94-3100-11e3-98e7-05ace80fa036.PNG)

Indeed, we can see that StatusCode is not equals to HttpStatus.OK. 

Have you ever encountered this problem? Moreover, this issue occurs when I delete a contact from a list, the status in this case is "No content, No content"...

Thank's :) 
Damdirt

**Comment by egaiter** [comment]
This issue was fixed with https://github.com/constantcontact/.net-sdk/commit/637a7171e88c493ec04c4e4c06da949e3502da90
