### ISSUE TITLE
GetContacts method does not URL encode parameters (specifically email address).

### ISSUE THREAD

**Issue by driedl** [constantcontact/.net-sdk#20]
So I'm pretty sure i've uncovered a larger issue with the SDK that should be looked into. That is, when the SDK created its URLS to pass though to the API, it does not URL encode critical parameters. In my case, its the email address on calls to GetContacts(string email, ...)

It is VERY common these days for emails to have the "+" symbol ever since gmail has supported the "myemail+[anything]@gmail.com" as a way to set up inbox rules...

When you fix this bug, i'd consider sweeping the code for all cases where you generate urls from userdata and make sure they get url encoded.

**Comment by csciuto** [comment]
This is duplicated by https://github.com/constantcontact/.net-sdk/pull/21 which is fixed.

**Comment by csciuto** [comment]
Resolved in https://github.com/constantcontact/.net-sdk/pull/21
