### ISSUE TITLE
AccountSummary is missing Company Logo

### ISSUE THREAD

**Issue by csciuto** [constantcontact/.net-sdk#39]
See http://developer.constantcontact.com/docs/account/summary-information-api.html and https://github.com/constantcontact/.net-sdk/blob/341e45335581a390526068a3fc4912541c30c004/CTCTWrapper/Components/AccountService/AccountSummaryInformation.cs

**Comment by bvysocky** [comment]
Fixed by commit 37673ad6dfe51512ab75298df4336d6cee77a2ad
