### ISSUE TITLE
ArchiveURL, Archivestatus still in SDK

### ISSUE THREAD

**Issue by csciuto** [constantcontact/.net-sdk#44]
A developer brought up the issue in this community post:
https://community.constantcontact.com/t5/Developer-Support-ask-questions/ArchiveURL-missing-from-Campaign-details-in-API-v2/m-p/229439#M9145

They always return null, but it's raising questions with developers, causing confusion, hesitation. 

We have by design removed support for email campaign archive_url and archive_status in AppConnect, but the functions still exist.

See https://github.com/constantcontact/.net-sdk/blob/master/CTCTWrapper/Components/EmailCampaigns/EmailCampaign.cs

**Comment by bvysocky** [comment]
Fixes merged
