### ISSUE TITLE
What does "Add the CTCT.dll library to your references project." mean?

### ISSUE THREAD

**Issue by nueverest** [constantcontact/.net-sdk#49]
Pardon my ignorance, but how do I "Add the CTCT.dll library to your references project."?

**Comment by nueverest** [comment]
I found [this forum posts helpful] (https://community.constantcontact.com/t5/Getting-Started-with-API-s/missing-ctct-dll-for-net-API/td-p/77957).

However, after adding the generated CTCT.dll to the references folder I'm still getting a build error.  
```
The type or namespace name 'ConstantContact' 
could not be found (are you missing a using directive or an assembly reference?)
```

This is for `Form1.cs` lines 19 and 51 under the CTCTWrapper_EmailCampaign.

**Comment by nueverest** [comment]
When I download the zip file there are 4 folders. 

1. If I open the solution inside of EmailCampaignExample and try to build it I get the errors above.
2. If I open the solution inside of CTCTWrapper and try to build it I get a warning message `A project with an Output Type of Class Library cannot be started directly. In order to debug this project, add an executable project to this solution which references the library project. Set the executable project as the startup project.`
3. If I open the solution under the folder `ContactExample` the build works properly.

Am I only supposed to be using the solution under `Contact Example`?  If you so could you update the README to be more clear on this point?  I was under the impression that all three directories contained working examples.

**Comment by bvysocky** [comment]
I have committed a fix for the Email Campaign Example, I apologize for it not being up to date.
I have also updated the readme to specify that it is the CTCTWrapper project that needs to be built to generate the CTCT.dll.
I hope you are finding our SDK helpful. Please feel free to contact api support if you have any more issues at Webservices@constantcontact.com
