### ISSUE TITLE
Creating items via POST

### ISSUE THREAD

**Issue by nueverest** [constantcontact/.net-sdk#52]
On [this page](https://constantcontact.mashery.com/io-docs) it allows me to create items via POST. For instance, I can create a Contact List, Email Campaign, or Add a new contact to a list.

How do I do that with this API?

I've added a [question on stackoverflow](http://stackoverflow.com/questions/31595352/using-the-constant-contact-c-sharp-net-sdk-v2-to-create-add).

**Comment by sergiugirnet** [comment]
You can find the API usage [here](https://github.com/constantcontact/.net-sdk)

1 Register for an API Key [here](https://constantcontact.mashery.com/apps/register)
2 Obtain an Access Token from [here](https://constantcontact.mashery.com/apps/mykeys)
3 Create a constantContactFactory object

private string _apiKey = "xxxxxxxxx"; 
private string _accessToken = "xxxx-xxxxx-xxxxx-xxxx"; 

IUserServiceContext userServiceContext = new UserServiceContext(_accessToken, _apiKey);
var constantContactFactory = new ConstantContactFactory(userServiceContext);

4 Create needed services, ex: create contact service

IContactService contactService = constantContactFactory.CreateContactService();

5 Call service methods, ex: get a contact by ID

var contact = contactService.GetContact("xxxxxxx");

**Comment by nueverest** [comment]
This does not seem to answer my question.  The question is about ```POST``` as opposed to ```GET```.
